#:schema node_modules/wrangler/config-schema.json
name = "blog"
compatibility_date = "2025-09-30"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next"

[assets]
directory = ".open-next/assets"